CascadeSelect - basic tests
primefaces-extensions/primefaces-integration-tests pull request #125
Opened 2021-03-07 16:33 UTC by christophs78

2021-03-07 16:36 UTC, melloware requested changes

2021-03-07 16:36 UTC, melloware commented on src/main/java/org/primefaces/extensions/integrationtests/cascadeselect/CascadeSelect001.java
> +        FacesContext.getCurrentInstance().addMessage(null, message);
I have a handy `TestUtils.addMessage()` to reduce a lot of this boilerplate of creating INFO messages.

2021-03-07 16:36 UTC, melloware commented on src/main/java/org/primefaces/extensions/integrationtests/cascadeselect/CascadeSelect002.java
> +        FacesContext.getCurrentInstance().addMessage(null, message);
Same here

2021-03-07 16:36 UTC, melloware commented on src/main/java/org/primefaces/extensions/integrationtests/cascadeselect/CascadeSelect002.java
> +
maybe make an `AbstractCascadeSelect` class to reduce some of this copy and paste?

2021-03-07 16:42 UTC, christophs78 commented on src/main/java/org/primefaces/extensions/integrationtests/cascadeselect/CascadeSelect001.java
> +        FacesContext.getCurrentInstance().addMessage(null, message);
good point!

2021-03-07 16:54 UTC, christophs78 commented on src/main/java/org/primefaces/extensions/integrationtests/cascadeselect/CascadeSelect002.java
> +
Not sure there are redundancies we can refactor. CascadeSelect001 only uses labels for SelectItems. CascadeSelect001 adds values and labels to SelectItems.

2021-03-07 17:05 UTC, melloware commented
OK do these tests need my NPE fix for them to pass?

2021-03-07 17:18 UTC, christophs78 commented
> OK do these tests need my NPE fix for them to pass?

No. But we need to fix https://github.com/primefaces/primefaces/issues/7082 for this tests to pass.

2021-03-07 18:08 UTC, melloware commented
OK submitted fix for 7082 and it does handle converters.

2021-03-07 18:33 UTC, christophs78 commented
> OK submitted fix for 7082 and it does handle converters.

Thanks for working on this! IMO this was kind of a showstopper which made this new component almost unusable.

2021-03-07 18:34 UTC, melloware commented
I totally agree I think Thomas will agree too and merge that fix tomorrow.

2021-03-08 09:00 UTC, christophs78 commented
I have to check this PR later this day. Probably there´s some issue with my  CascaseSelect-PF-Selenium-wrapper.

2021-03-09 14:16 UTC, merged

2021-03-09 16:26 UTC, melloware commented
All tests passing and I just added tests for show/hide/enable/disable widget methods.