DataTable: reproducer for PF 5481
primefaces-extensions/primefaces-integration-tests pull request #32
Opened 2020-09-05 19:56 UTC by christophs78

https://github.com/primefaces/primefaces/issues/5481

2020-09-05 21:51 UTC, melloware requested changes

2020-09-05 21:51 UTC, melloware commented on src/test/java/org/primefaces/extensions/integrationtests/datatable/DataTable009Test.java
> +    @DisplayName("DataTable: filter - issue 1390")
Maybe full HTTP link to issue 1391 in the DisplayName?

2020-09-05 21:51 UTC, melloware commented on src/test/java/org/primefaces/extensions/integrationtests/datatable/DataTable008Test.java
> +    @DisplayName("DataTable: filter - issue 5481")
Same full link to 5481 in DisplayName?

2020-09-07 13:17 UTC, melloware requested changes

2020-09-07 13:17 UTC, melloware commented on src/test/java/org/primefaces/extensions/integrationtests/datatable/DataTable008Test.java
> +        //TODO: move some filter-logic to PF Selenium?
I agree with you i feel like we should add filter code to PF Selenium to prevent some of this boilerplate code?

2020-09-07 16:19 UTC, christophs78 commented on src/test/java/org/primefaces/extensions/integrationtests/datatable/DataTable008Test.java
> +        //TODO: move some filter-logic to PF Selenium?
Yep. Just need to find time the next days.

2020-09-09 14:59 UTC, melloware commented
I assume this test case is supposed to fail until we fix the main PF issue?

2020-09-09 15:38 UTC, christophs78 commented
Yes

2020-09-09 19:49 UTC, christophs78 commented
@melloware : Is there a way to re-run a Travis CI - build without pushing a commit?

2020-09-09 19:53 UTC, melloware commented
This is the only way..
```
git commit --allow-empty -m "Trigger"
```

2020-09-14 22:22 UTC, merged